name: lixiangyu
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.0
  cached_network_image: ^3.0.0
  flutter_pickers: ^2.1.1
  dio: ^4.0.0
  flutter_swiper: ^1.1.6
  flutter_splash_screen: ^0.1.0
  fluttertoast: ^8.0.7
  flutter_webview_plugin: ^0.3.11
  lpinyin: ^2.0.3
  package_info: ^2.0.0
  flutter_screenutil: ^5.0.0+2
  dio_cookie_manager: ^2.0.0
  share: ^2.0.2
  json_annotation: ^4.0.1
  modal_bottom_sheet: ^2.0.0
  animated_text_kit: ^4.2.1
  fluro: ^2.0.3
  extended_text_field: ^8.0.0
  shared_preferences: ^2.0.6
  event_bus: ^2.0.0
  image_picker: ^0.7.5+3
  interactiveviewer_gallery: ^0.5.0
  flutter_easyrefresh: ^2.2.1
  path: ^1.8.0
  azlistview: ^1.1.1
  chips_choice: ^2.0.1
  flutter_plugin_record: ^1.0.1
  fluwx: ^3.4.2
  webview_flutter: ^2.0.9
  loading_animations: ^2.2.0
  ff_stars: ^0.2.0
  web_socket_channel: ^2.1.0
  flutter_lc_im: ^1.1.4
  permission_handler: ^4.4.0+hotfix.2
  audioplayers: ^0.19.0
  photo_view: ^0.11.1
  video_player: ^2.1.6
  video_thumbnail: ^0.3.3
  pull_to_refresh: ^2.0.0
  badges: ^2.0.1
  tobias: ^2.1.0
  flutter_seekbar: ^0.0.1
  flutter_rating_bar: ^4.0.0
  marquee: ^2.2.0

  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - mock/
    - assets/images/chat/
    - assets/icons/人民币.png
    - assets/images/home/qiandao.png
    - assets/images/home/touxiang.jpeg
    - assets/images/home/jinbi.gif
    - assets/images/home/fenlei.jpeg
    - assets/images/home/分类背景.jpeg
    - assets/images/home/分类背景.gif
    - assets/images/publish/banma.png
    - assets/images/my/设置.png
    - assets/images/my/icon_right.png
    - assets/images/my/image_01.png
    - assets/images/publish/icon_add.png
    - assets/images/publish/icon_gif.png
    - assets/images/publish/icon_image.webp
    - assets/images/publish/icon_right.png
    - assets/images/publish/icon_topic.png
    - assets/images/publish/mine_feedback_ic_del.png
    - assets/images/publish/mine_feedback_add_image.png
    - assets/images/publish/icon_emotion.png
    - assets/images/publish/icon_mention.png
    - assets/images/publish/icon_emoji_delete.png
    - assets/images/publish/voice_volume_1.png
    - assets/images/publish/voice_volume_2.png
    - assets/images/publish/voice_volume_3.png
    - assets/images/publish/voice_volume_4.png
    - assets/images/publish/voice_volume_5.png
    - assets/images/publish/voice_volume_6.png
    - assets/images/publish/voice_volume_7.png
    - assets/images/home/start.jpeg
    - assets/images/details/orangeNormal.png
    - assets/images/details/orangeSelected.png
    - assets/images/details/注意事项.jpeg
    - assets/images/details/接单流程.png
    - assets/images/details/常见问题.jpeg
    - assets/images/pay/支付宝.jpeg
    - assets/images/pay/微信.jpeg
    - assets/images/pay/对勾.jpeg
    - assets/images/purse/钱包.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
          weight: 400 # normal
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf

